# Generated by Django 6.0.6 on 2026-06-13 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('service', 'Qualité de service'), ('agent', 'Comportement agent'), ('property', 'Information bien erronée'), ('transaction', 'Problème transaction'), ('other', 'Autre')], default='other', max_length=30)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En traitement'), ('resolved', 'Résolue'), ('closed', 'Clôturée')], default='open', max_length=20)),
                ('owner_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='agencies.agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='properties.property')),
            ],
            options={
                'verbose_name': 'Plainte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default="J'aimerais en savoir un peu plus sur ce bien.")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('read', 'Lu'), ('replied', 'Répondu'), ('closed', 'Clôturé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='agencies.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='properties.property')),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interactions.contactrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField()),
                ('rescheduled_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rescheduled', 'Reprogrammée'), ('rejected', 'Rejetée'), ('done', 'Effectuée')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('agent_notes', models.TextField(blank=True, help_text='Notes ou motif de rejet/reprogrammation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_requests', to='agencies.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='properties.property')),
            ],
            options={
                'verbose_name': 'Demande de visite',
                'ordering': ['-created_at'],
            },
        ),
    ]
