# Generated by Django 6.0.5 on 2026-05-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('clients', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Vente'), ('rent', 'Location'), ('purchase', 'Achat')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('completed', 'Complété'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='agencies.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='clients.client')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='properties.property')),
            ],
            options={
                'verbose_name': 'Transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('sale_contract', 'Contrat de Vente'), ('lease_contract', 'Contrat de Bail'), ('purchase_contract', "Contrat d'Achat"), ('preliminary', 'Avant-Contrat'), ('mandate', 'Mandat')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('signed', 'Signé'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Contrat',
                'ordering': ['-created_at'],
            },
        ),
    ]
